/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.AddAllbooksToList;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

import view.Login;
import control.EmailValidator;
import control.LoginController;
import control.MobileValidator;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author EACMS
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    PreparedStatement pstmt;
    int xMouse;
    int yMouse;
    public int USERID_HomePage;
    public int BookId_HomePage;
    private String userPASSWORD_DB_Homepage;
    public ArrayList<Books> bookList = bookListfun();
    ArrayList<Books> borrowedBookslist = bookListfun();
    ArrayList<Books> borrowedBooklist = new ArrayList<>();

    public void setUSERID_HomePage(int USERID_HomePage) {
        this.USERID_HomePage = USERID_HomePage;
    }

    public HomePage() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
        showBooks();

        //changing table header
        tabel_books.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 15));
        tabel_books.getTableHeader().setOpaque(false);
        tabel_books.getTableHeader().setBackground(new Color(102, 153, 255));
        tabel_books.getTableHeader().setForeground(new Color(0, 0, 34));

        borrowed_Books_table.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 15));
        borrowed_Books_table.getTableHeader().setOpaque(false);
        borrowed_Books_table.getTableHeader().setBackground(new Color(102, 153, 255));
        borrowed_Books_table.getTableHeader().setForeground(new Color(0, 0, 34));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dragLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        logoutLabel = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        BookListLabel = new javax.swing.JLabel();
        borrowedbooksLanel = new javax.swing.JLabel();
        aboutLabel = new javax.swing.JLabel();
        contactLabel = new javax.swing.JLabel();
        profileLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        panelWithTheTable = new javax.swing.JPanel();
        all_Books_table = new javax.swing.JScrollPane();
        tabel_books = new javax.swing.JTable();
        ContactPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        borrowedBooks = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        borrowed_Books_table = new javax.swing.JTable();
        profilePanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        user_email_proPage = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        user_fullname_proPage = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        user_userName_proPage = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        user_mobile_proPage = new javax.swing.JTextField();
        profilepage_passwordPanel = new javax.swing.JPanel();
        user_newPWReEnter_proPage = new javax.swing.JPasswordField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        user_currentPW_proPage = new javax.swing.JPasswordField();
        user_newPW_proPage = new javax.swing.JPasswordField();
        savePW_In_Profile = new javax.swing.JButton();
        changepw_errorMSG = new javax.swing.JLabel();
        changePW_Homepage_Profile = new javax.swing.JLabel();
        edit_profile_Button_profilePage = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        delete_user_label_profilePage = new javax.swing.JLabel();
        save_profile_button_ProfilePage = new javax.swing.JButton();
        edit_user_error_msg_proMsg = new javax.swing.JLabel();
        aboutPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        bookViewPanel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        authorName_label = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        bookName_Label = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        PublishedDate_label = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        discriptionTextArea = new javax.swing.JTextArea();
        imagePanelInBookView = new javax.swing.JPanel();
        bookBorrow_Button = new javax.swing.JButton();
        return_Book_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1045, 650));

        dragLabel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                dragLabelMouseDragged(evt);
            }
        });
        dragLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dragLabelMousePressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 34));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel2.setBackground(new java.awt.Color(0, 0, 34));

        jPanel3.setBackground(new java.awt.Color(0, 0, 34));

        jLabel2.setFont(new java.awt.Font("Georgia", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Book Browser");

        jLabel1.setFont(new java.awt.Font("Gabriola", 2, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Make your future Bright..");

        logoutLabel.setBackground(new java.awt.Color(0, 0, 34));
        logoutLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        logoutLabel.setForeground(new java.awt.Color(204, 204, 204));
        logoutLabel.setText("LogOut");
        logoutLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutLabel.setOpaque(true);
        logoutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutLabelMouseClicked(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(0, 0, 20));

        BookListLabel.setBackground(new java.awt.Color(35, 115, 230));
        BookListLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        BookListLabel.setForeground(new java.awt.Color(255, 255, 255));
        BookListLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BookListLabel.setText("Book List");
        BookListLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BookListLabel.setOpaque(true);
        BookListLabel.setPreferredSize(new java.awt.Dimension(144, 24));
        BookListLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BookListLabelMouseClicked(evt);
            }
        });

        borrowedbooksLanel.setBackground(new java.awt.Color(0, 0, 20));
        borrowedbooksLanel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        borrowedbooksLanel.setForeground(new java.awt.Color(255, 255, 255));
        borrowedbooksLanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        borrowedbooksLanel.setText("Borrowed Books");
        borrowedbooksLanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        borrowedbooksLanel.setOpaque(true);
        borrowedbooksLanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                borrowedbooksLanelMouseClicked(evt);
            }
        });

        aboutLabel.setBackground(new java.awt.Color(0, 0, 20));
        aboutLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        aboutLabel.setForeground(new java.awt.Color(255, 255, 255));
        aboutLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aboutLabel.setText("About");
        aboutLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aboutLabel.setOpaque(true);
        aboutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutLabelMouseClicked(evt);
            }
        });

        contactLabel.setBackground(new java.awt.Color(0, 0, 20));
        contactLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        contactLabel.setForeground(new java.awt.Color(255, 255, 255));
        contactLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        contactLabel.setText("Contact");
        contactLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        contactLabel.setOpaque(true);
        contactLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contactLabelMouseClicked(evt);
            }
        });

        profileLabel.setBackground(new java.awt.Color(0, 0, 20));
        profileLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        profileLabel.setForeground(new java.awt.Color(255, 255, 255));
        profileLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profileLabel.setText("Profile");
        profileLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        profileLabel.setOpaque(true);
        profileLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(BookListLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(borrowedbooksLanel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(profileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(contactLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(aboutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(BookListLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(aboutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(contactLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(borrowedbooksLanel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(profileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel4.setBackground(new java.awt.Color(0, 0, 34));
        jLabel4.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("X");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.setOpaque(true);
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(logoutLabel)
                        .addGap(66, 66, 66)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(logoutLabel))
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel4.setBackground(new java.awt.Color(0, 0, 34));
        jPanel4.setLayout(new java.awt.CardLayout());

        panelWithTheTable.setBackground(new java.awt.Color(0, 0, 34));
        panelWithTheTable.setPreferredSize(new java.awt.Dimension(1050, 500));

        all_Books_table.setBackground(new java.awt.Color(0, 0, 34));

        tabel_books.setBackground(new java.awt.Color(255, 255, 255));
        tabel_books.setFont(new java.awt.Font("Garamond", 0, 18)); // NOI18N
        tabel_books.setForeground(new java.awt.Color(0, 0, 102));
        tabel_books.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book Name", "Author Name", "Published Date"
            }
        ));
        tabel_books.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabel_books.setGridColor(new java.awt.Color(255, 255, 255));
        tabel_books.setRowHeight(25);
        tabel_books.setSelectionBackground(new java.awt.Color(195, 226, 255));
        tabel_books.setSelectionForeground(new java.awt.Color(0, 0, 51));
        tabel_books.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_booksMouseClicked(evt);
            }
        });
        all_Books_table.setViewportView(tabel_books);

        javax.swing.GroupLayout panelWithTheTableLayout = new javax.swing.GroupLayout(panelWithTheTable);
        panelWithTheTable.setLayout(panelWithTheTableLayout);
        panelWithTheTableLayout.setHorizontalGroup(
            panelWithTheTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(all_Books_table, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1050, Short.MAX_VALUE)
        );
        panelWithTheTableLayout.setVerticalGroup(
            panelWithTheTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelWithTheTableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(all_Books_table)
                .addContainerGap())
        );

        jPanel4.add(panelWithTheTable, "card2");

        ContactPanel.setBackground(new java.awt.Color(0, 0, 34));
        ContactPanel.setPreferredSize(new java.awt.Dimension(1050, 500));

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Contact ");

        jLabel5.setText("contact information");

        javax.swing.GroupLayout ContactPanelLayout = new javax.swing.GroupLayout(ContactPanel);
        ContactPanel.setLayout(ContactPanelLayout);
        ContactPanelLayout.setHorizontalGroup(
            ContactPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContactPanelLayout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(ContactPanelLayout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(jLabel5)
                .addContainerGap(722, Short.MAX_VALUE))
        );
        ContactPanelLayout.setVerticalGroup(
            ContactPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContactPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel6)
                .addGap(45, 45, 45)
                .addComponent(jLabel5)
                .addContainerGap(352, Short.MAX_VALUE))
        );

        jPanel4.add(ContactPanel, "card3");

        borrowedBooks.setBackground(new java.awt.Color(0, 0, 34));
        borrowedBooks.setPreferredSize(new java.awt.Dimension(1050, 500));

        jScrollPane4.setBackground(new java.awt.Color(0, 0, 34));

        borrowed_Books_table.setBackground(new java.awt.Color(255, 255, 255));
        borrowed_Books_table.setFont(new java.awt.Font("Garamond", 0, 18)); // NOI18N
        borrowed_Books_table.setForeground(new java.awt.Color(0, 0, 102));
        borrowed_Books_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book Name", "Author Name", "Published Date"
            }
        ));
        borrowed_Books_table.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        borrowed_Books_table.setGridColor(new java.awt.Color(255, 255, 255));
        borrowed_Books_table.setRowHeight(25);
        borrowed_Books_table.setSelectionBackground(new java.awt.Color(195, 226, 255));
        borrowed_Books_table.setSelectionForeground(new java.awt.Color(0, 0, 51));
        borrowed_Books_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                borrowed_Books_tableMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(borrowed_Books_table);

        javax.swing.GroupLayout borrowedBooksLayout = new javax.swing.GroupLayout(borrowedBooks);
        borrowedBooks.setLayout(borrowedBooksLayout);
        borrowedBooksLayout.setHorizontalGroup(
            borrowedBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1050, Short.MAX_VALUE)
        );
        borrowedBooksLayout.setVerticalGroup(
            borrowedBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(borrowedBooksLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
        );

        jPanel4.add(borrowedBooks, "card3");

        profilePanel.setBackground(new java.awt.Color(0, 0, 34));
        profilePanel.setPreferredSize(new java.awt.Dimension(1050, 500));

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Profile");

        user_email_proPage.setBackground(new java.awt.Color(0, 0, 34));
        user_email_proPage.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        user_email_proPage.setForeground(new java.awt.Color(255, 255, 255));
        user_email_proPage.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        user_email_proPage.setBorder(null);
        user_email_proPage.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        user_email_proPage.setFocusable(false);
        user_email_proPage.setMaximumSize(new java.awt.Dimension(328, 2147483647));
        user_email_proPage.setOpaque(false);

        jLabel16.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 204, 204));
        jLabel16.setText("Email");

        jLabel17.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 204, 204));
        jLabel17.setText("Full Name");

        user_fullname_proPage.setBackground(new java.awt.Color(0, 0, 34));
        user_fullname_proPage.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        user_fullname_proPage.setForeground(new java.awt.Color(255, 255, 255));
        user_fullname_proPage.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        user_fullname_proPage.setBorder(null);
        user_fullname_proPage.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        user_fullname_proPage.setFocusable(false);
        user_fullname_proPage.setOpaque(false);

        jLabel18.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 204, 204));
        jLabel18.setText("User Name");

        user_userName_proPage.setBackground(new java.awt.Color(0, 0, 34));
        user_userName_proPage.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        user_userName_proPage.setForeground(new java.awt.Color(255, 255, 255));
        user_userName_proPage.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        user_userName_proPage.setBorder(null);
        user_userName_proPage.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        user_userName_proPage.setFocusable(false);
        user_userName_proPage.setOpaque(false);

        jLabel19.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 204, 204));
        jLabel19.setText("Mobile");

        user_mobile_proPage.setBackground(new java.awt.Color(0, 0, 34));
        user_mobile_proPage.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        user_mobile_proPage.setForeground(new java.awt.Color(255, 255, 255));
        user_mobile_proPage.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        user_mobile_proPage.setBorder(null);
        user_mobile_proPage.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        user_mobile_proPage.setFocusable(false);
        user_mobile_proPage.setOpaque(false);

        profilepage_passwordPanel.setBackground(new java.awt.Color(0, 0, 34));

        user_newPWReEnter_proPage.setBackground(new java.awt.Color(0, 0, 34));
        user_newPWReEnter_proPage.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        user_newPWReEnter_proPage.setForeground(new java.awt.Color(255, 255, 255));
        user_newPWReEnter_proPage.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        user_newPWReEnter_proPage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));
        user_newPWReEnter_proPage.setOpaque(false);

        jLabel20.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 204, 204));
        jLabel20.setText("Current Password");

        jLabel21.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 204, 204));
        jLabel21.setText("New Password");

        jLabel22.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 204, 204));
        jLabel22.setText("Re-Enter New Password");

        user_currentPW_proPage.setBackground(new java.awt.Color(0, 0, 34));
        user_currentPW_proPage.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        user_currentPW_proPage.setForeground(new java.awt.Color(255, 255, 255));
        user_currentPW_proPage.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        user_currentPW_proPage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204)));
        user_currentPW_proPage.setOpaque(false);

        user_newPW_proPage.setBackground(new java.awt.Color(0, 0, 34));
        user_newPW_proPage.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        user_newPW_proPage.setForeground(new java.awt.Color(255, 255, 255));
        user_newPW_proPage.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        user_newPW_proPage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204)));
        user_newPW_proPage.setOpaque(false);

        savePW_In_Profile.setBackground(new java.awt.Color(35, 115, 230));
        savePW_In_Profile.setForeground(new java.awt.Color(0, 0, 51));
        savePW_In_Profile.setText("Save");
        savePW_In_Profile.setBorder(null);
        savePW_In_Profile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        savePW_In_Profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                savePW_In_ProfileMouseClicked(evt);
            }
        });

        changepw_errorMSG.setBackground(new java.awt.Color(0, 0, 34));
        changepw_errorMSG.setForeground(new java.awt.Color(255, 0, 0));
        changepw_errorMSG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        changepw_errorMSG.setToolTipText("");

        javax.swing.GroupLayout profilepage_passwordPanelLayout = new javax.swing.GroupLayout(profilepage_passwordPanel);
        profilepage_passwordPanel.setLayout(profilepage_passwordPanelLayout);
        profilepage_passwordPanelLayout.setHorizontalGroup(
            profilepage_passwordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilepage_passwordPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(profilepage_passwordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profilepage_passwordPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(savePW_In_Profile, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(profilepage_passwordPanelLayout.createSequentialGroup()
                        .addGroup(profilepage_passwordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel21)
                            .addComponent(jLabel20))
                        .addGap(18, 18, 18)
                        .addGroup(profilepage_passwordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(changepw_errorMSG, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(profilepage_passwordPanelLayout.createSequentialGroup()
                                .addGroup(profilepage_passwordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(user_currentPW_proPage, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(user_newPWReEnter_proPage, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(user_newPW_proPage, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        profilepage_passwordPanelLayout.setVerticalGroup(
            profilepage_passwordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilepage_passwordPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(profilepage_passwordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(user_currentPW_proPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(profilepage_passwordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(user_newPW_proPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(profilepage_passwordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(user_newPWReEnter_proPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(changepw_errorMSG, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(savePW_In_Profile, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        changePW_Homepage_Profile.setBackground(new java.awt.Color(0, 0, 34));
        changePW_Homepage_Profile.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        changePW_Homepage_Profile.setForeground(new java.awt.Color(0, 204, 204));
        changePW_Homepage_Profile.setText("Change Password");
        changePW_Homepage_Profile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        changePW_Homepage_Profile.setOpaque(true);
        changePW_Homepage_Profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changePW_Homepage_ProfileMouseClicked(evt);
            }
        });

        edit_profile_Button_profilePage.setBackground(new java.awt.Color(35, 115, 230));
        edit_profile_Button_profilePage.setForeground(new java.awt.Color(0, 0, 51));
        edit_profile_Button_profilePage.setText("Edit Profile");
        edit_profile_Button_profilePage.setBorder(null);
        edit_profile_Button_profilePage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        edit_profile_Button_profilePage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edit_profile_Button_profilePageMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 174, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 154, Short.MAX_VALUE)
        );

        delete_user_label_profilePage.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        delete_user_label_profilePage.setForeground(new java.awt.Color(255, 51, 51));
        delete_user_label_profilePage.setText("Delete User Account");
        delete_user_label_profilePage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete_user_label_profilePage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delete_user_label_profilePageMouseClicked(evt);
            }
        });

        save_profile_button_ProfilePage.setBackground(new java.awt.Color(35, 115, 230));
        save_profile_button_ProfilePage.setForeground(new java.awt.Color(0, 0, 51));
        save_profile_button_ProfilePage.setText("Save");
        save_profile_button_ProfilePage.setBorder(null);
        save_profile_button_ProfilePage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        save_profile_button_ProfilePage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                save_profile_button_ProfilePageMouseClicked(evt);
            }
        });

        edit_user_error_msg_proMsg.setForeground(new java.awt.Color(255, 0, 0));
        edit_user_error_msg_proMsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout profilePanelLayout = new javax.swing.GroupLayout(profilePanel);
        profilePanel.setLayout(profilePanelLayout);
        profilePanelLayout.setHorizontalGroup(
            profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilePanelLayout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(profilePanelLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(profilePanelLayout.createSequentialGroup()
                        .addComponent(delete_user_label_profilePage)
                        .addGap(124, 124, 124)
                        .addComponent(edit_profile_Button_profilePage, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                        .addComponent(save_profile_button_ProfilePage, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(profilePanelLayout.createSequentialGroup()
                        .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel16)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19))
                        .addGap(39, 39, 39)
                        .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(user_email_proPage, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                                .addComponent(user_fullname_proPage, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                                .addComponent(user_userName_proPage, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                                .addComponent(user_mobile_proPage, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(profilePanelLayout.createSequentialGroup()
                        .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(profilepage_passwordPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(changePW_Homepage_Profile))
                        .addContainerGap(25, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profilePanelLayout.createSequentialGroup()
                        .addComponent(edit_user_error_msg_proMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100))))
        );
        profilePanelLayout.setVerticalGroup(
            profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilePanelLayout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(profilePanelLayout.createSequentialGroup()
                        .addComponent(changePW_Homepage_Profile)
                        .addGap(18, 18, 18)
                        .addComponent(profilepage_passwordPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profilePanelLayout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(user_email_proPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(user_fullname_proPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(user_userName_proPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(user_mobile_proPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(profilePanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(edit_user_error_msg_proMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(122, 122, 122))
                            .addGroup(profilePanelLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(delete_user_label_profilePage, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(edit_profile_Button_profilePage, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(save_profile_button_ProfilePage, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );

        jPanel4.add(profilePanel, "card3");

        aboutPanel.setBackground(new java.awt.Color(0, 0, 34));
        aboutPanel.setPreferredSize(new java.awt.Dimension(1050, 500));

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("About");

        jLabel8.setText("About information");

        javax.swing.GroupLayout aboutPanelLayout = new javax.swing.GroupLayout(aboutPanel);
        aboutPanel.setLayout(aboutPanelLayout);
        aboutPanelLayout.setHorizontalGroup(
            aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutPanelLayout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(aboutPanelLayout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(jLabel8)
                .addContainerGap(731, Short.MAX_VALUE))
        );
        aboutPanelLayout.setVerticalGroup(
            aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel7)
                .addGap(45, 45, 45)
                .addComponent(jLabel8)
                .addContainerGap(352, Short.MAX_VALUE))
        );

        jPanel4.add(aboutPanel, "card3");

        bookViewPanel.setBackground(new java.awt.Color(0, 0, 34));
        bookViewPanel.setPreferredSize(new java.awt.Dimension(1050, 500));

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 204, 204));
        jLabel13.setText("Book Name");

        authorName_label.setBackground(new java.awt.Color(0, 0, 34));
        authorName_label.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        authorName_label.setForeground(new java.awt.Color(255, 255, 255));
        authorName_label.setText("Name of the book");
        authorName_label.setBorder(null);
        authorName_label.setFocusable(false);

        jLabel14.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 204, 204));
        jLabel14.setText("Author Name");

        bookName_Label.setBackground(new java.awt.Color(0, 0, 34));
        bookName_Label.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        bookName_Label.setForeground(new java.awt.Color(255, 255, 255));
        bookName_Label.setText("Name of the book");
        bookName_Label.setBorder(null);
        bookName_Label.setFocusable(false);

        jLabel15.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 204, 204));
        jLabel15.setText("Published Date");

        PublishedDate_label.setBackground(new java.awt.Color(0, 0, 34));
        PublishedDate_label.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        PublishedDate_label.setForeground(new java.awt.Color(255, 255, 255));
        PublishedDate_label.setText("Name of the book");
        PublishedDate_label.setBorder(null);
        PublishedDate_label.setFocusable(false);

        discriptionTextArea.setBackground(new java.awt.Color(0, 0, 34));
        discriptionTextArea.setColumns(20);
        discriptionTextArea.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        discriptionTextArea.setForeground(new java.awt.Color(255, 255, 255));
        discriptionTextArea.setLineWrap(true);
        discriptionTextArea.setRows(5);
        discriptionTextArea.setText("dfgderuhjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjlhasdfhajshdfjshadfjhasjdfhjhskjdhfjashddshhsjajdfhsljhdfjshdjfhkajshdfjkhaskjfhdjklashdfjklhkljsahdfhaslkjhdfjh");
        discriptionTextArea.setWrapStyleWord(true);
        discriptionTextArea.setBorder(null);
        discriptionTextArea.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(discriptionTextArea);

        imagePanelInBookView.setOpaque(false);

        javax.swing.GroupLayout imagePanelInBookViewLayout = new javax.swing.GroupLayout(imagePanelInBookView);
        imagePanelInBookView.setLayout(imagePanelInBookViewLayout);
        imagePanelInBookViewLayout.setHorizontalGroup(
            imagePanelInBookViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        imagePanelInBookViewLayout.setVerticalGroup(
            imagePanelInBookViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 201, Short.MAX_VALUE)
        );

        bookBorrow_Button.setBackground(new java.awt.Color(35, 115, 230));
        bookBorrow_Button.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        bookBorrow_Button.setForeground(new java.awt.Color(0, 0, 51));
        bookBorrow_Button.setText("Borrow");
        bookBorrow_Button.setBorder(null);
        bookBorrow_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bookBorrow_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookBorrow_ButtonMouseClicked(evt);
            }
        });

        return_Book_Button.setBackground(new java.awt.Color(35, 115, 230));
        return_Book_Button.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        return_Book_Button.setForeground(new java.awt.Color(0, 0, 51));
        return_Book_Button.setText("Return Book");
        return_Book_Button.setBorder(null);
        return_Book_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        return_Book_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                return_Book_ButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bookViewPanelLayout = new javax.swing.GroupLayout(bookViewPanel);
        bookViewPanel.setLayout(bookViewPanelLayout);
        bookViewPanelLayout.setHorizontalGroup(
            bookViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookViewPanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(bookViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(bookViewPanelLayout.createSequentialGroup()
                        .addGroup(bookViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15))
                        .addGap(46, 46, 46)
                        .addGroup(bookViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bookName_Label, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                            .addComponent(authorName_label)
                            .addComponent(PublishedDate_label)))
                    .addComponent(imagePanelInBookView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(bookViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bookViewPanelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bookViewPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(return_Book_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bookBorrow_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        bookViewPanelLayout.setVerticalGroup(
            bookViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bookViewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bookViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imagePanelInBookView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(bookViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(bookName_Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(bookViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(authorName_label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(bookViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(PublishedDate_label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(return_Book_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookBorrow_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jPanel4.add(bookViewPanel, "card3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1045, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dragLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 880, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(159, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1045, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 659, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(dragLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 575, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //books for book list all books
    public ArrayList<Books> bookListfun() {
        
//        System.out.println("list in view booklistfun" + bookList);
        return AddAllbooksToList.bookList();
    }

    public void showBooks() {
        DefaultTableModel model = (DefaultTableModel) tabel_books.getModel();
        Object[] row = new Object[3];
        for (int i = 0; i < bookList.size(); i++) {
            row[0] = bookList.get(i).getBookName();
            row[1] = bookList.get(i).getAuthorName();
            row[2] = bookList.get(i).getPublishedDate();
            model.addRow(row);
        }
    }

    //for borrowed books table
    public ArrayList<Books> borrowedBookList() {
        borrowedBooklist.clear();
        borrowedBooklist = AddAllbooksToList.borrowedbooks(this.USERID_HomePage);
        System.out.println("after clean" + borrowedBooklist);
        return borrowedBooklist;
    }

    public void showBorrowedBooks() {
        System.out.println("show boro books");
        DefaultTableModel model = (DefaultTableModel) borrowed_Books_table.getModel();
        //to delete previous data
        model.setRowCount(0);
        Object[] row = new Object[3];
        for (int i = 0; i < borrowedBooklist.size(); i++) {
            row[0] = borrowedBooklist.get(i).getBookName();
            row[1] = borrowedBooklist.get(i).getAuthorName();
            row[2] = borrowedBooklist.get(i).getPublishedDate();
            model.addRow(row);
        }
    }


    private void dragLabelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragLabelMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);

    }//GEN-LAST:event_dragLabelMouseDragged

    private void dragLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragLabelMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_dragLabelMousePressed

    private void logoutLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLabelMouseClicked
        System.out.println("Loged Out..");
        Login log = new Login();
        log.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_logoutLabelMouseClicked

    private void BookListLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookListLabelMouseClicked
        //panel visibility

        borrowedBooks.setVisible(false);
        ContactPanel.setVisible(false);
        aboutPanel.setVisible(false);
        panelWithTheTable.setVisible(true);
        profilePanel.setVisible(false);
        bookViewPanel.setVisible(false);

        //---------changing the backgrounda color fo labels------------
        profileLabel.setBackground(new Color(0, 0, 20));
        borrowedbooksLanel.setBackground(new Color(0, 0, 20));
        BookListLabel.setBackground(new Color(35, 115, 230));
        contactLabel.setBackground(new Color(0, 0, 20));
        aboutLabel.setBackground(new Color(0, 0, 20));
    }//GEN-LAST:event_BookListLabelMouseClicked

    private void borrowedbooksLanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrowedbooksLanelMouseClicked
        borrowedBooks.setVisible(true);
        panelWithTheTable.setVisible(false);
        ContactPanel.setVisible(false);
        aboutPanel.setVisible(false);
        profilePanel.setVisible(false);
        bookViewPanel.setVisible(false);

        borrowedBookList();
        showBorrowedBooks();

        //---------changing the backgrounda color fo labels------------
        profileLabel.setBackground(new Color(0, 0, 20));
        borrowedbooksLanel.setBackground(new Color(35, 115, 230));
        BookListLabel.setBackground(new Color(0, 0, 20));
        contactLabel.setBackground(new Color(0, 0, 20));
        aboutLabel.setBackground(new Color(0, 0, 20));

    }//GEN-LAST:event_borrowedbooksLanelMouseClicked

    private void aboutLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutLabelMouseClicked
        //panel visibility

        borrowedBooks.setVisible(false);
        ContactPanel.setVisible(false);
        aboutPanel.setVisible(true);
        panelWithTheTable.setVisible(false);
        profilePanel.setVisible(false);
        bookViewPanel.setVisible(false);

        //---------changing the backgrounda color fo labels------------
        profileLabel.setBackground(new Color(0, 0, 20));
        borrowedbooksLanel.setBackground(new Color(0, 0, 20));
        BookListLabel.setBackground(new Color(0, 0, 20));
        contactLabel.setBackground(new Color(0, 0, 20));
        aboutLabel.setBackground(new Color(35, 115, 230));

    }//GEN-LAST:event_aboutLabelMouseClicked

    private void contactLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactLabelMouseClicked
        //-----------------------------panel visibility
        borrowedBooks.setVisible(false);
        ContactPanel.setVisible(true);
        aboutPanel.setVisible(false);
        panelWithTheTable.setVisible(false);
        profilePanel.setVisible(false);
        bookViewPanel.setVisible(false);

        //---------changing the backgrounda color fo labels------------
        borrowedbooksLanel.setBackground(new Color(0, 0, 20));
        BookListLabel.setBackground(new Color(0, 0, 20));
        contactLabel.setBackground(new Color(35, 115, 230));
        profileLabel.setBackground(new Color(0, 0, 20));
    }//GEN-LAST:event_contactLabelMouseClicked

    private void profileLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileLabelMouseClicked
        borrowedBooks.setVisible(false);
        ContactPanel.setVisible(false);
        aboutPanel.setVisible(false);
        panelWithTheTable.setVisible(false);
        profilePanel.setVisible(true);
        bookViewPanel.setVisible(false);
        profilepage_passwordPanel.setVisible(false);

        //---------changing the backgrounda color fo labels------------
        borrowedbooksLanel.setBackground(new Color(0, 0, 20));
        BookListLabel.setBackground(new Color(0, 0, 20));
        contactLabel.setBackground(new Color(0, 0, 20));
        aboutLabel.setBackground(new Color(0, 0, 20));
        profileLabel.setBackground(new Color(35, 115, 230));

        custamizeProfilePage();
    }//GEN-LAST:event_profileLabelMouseClicked
    private void custamizeProfilePage() {
        //profile edit save button
        save_profile_button_ProfilePage.setVisible(false);
        edit_profile_Button_profilePage.setVisible(true);

        this.edit_user_error_msg_proMsg.setText("");
        this.changepw_errorMSG.setText("");
        this.user_currentPW_proPage.setText("");
        this.user_newPW_proPage.setText("");
        this.user_newPWReEnter_proPage.setText("");
        //-----------to change cursor
        Cursor defCusor = new Cursor(Cursor.DEFAULT_CURSOR);

        user_email_proPage.setFocusable(false);
        user_fullname_proPage.setFocusable(false);
        user_mobile_proPage.setFocusable(false);
        user_userName_proPage.setFocusable(false);

        user_email_proPage.setCursor(defCusor);
        user_fullname_proPage.setCursor(defCusor);
        user_mobile_proPage.setCursor(defCusor);
        user_userName_proPage.setCursor(defCusor);

        displayUserDetails();
    }

    private void displayUserDetails() {
        try {
            // create our mysql database connection
            String myDriver = "com.mysql.cj.jdbc.Driver";
            // change the time zone to UTC
            String myUrl = "jdbc:mysql://localhost/java_login?serverTimezone=UTC";
            Class.forName(myDriver);
            Connection conn = DriverManager.getConnection(myUrl, "root", "");

            pstmt = conn.prepareStatement("SELECT * FROM users WHERE userId =?;");
            pstmt.setInt(1, this.USERID_HomePage);

            System.out.println("sql query " + pstmt.toString());
            ResultSet rs = pstmt.executeQuery();

            while (rs.next()) {
                String userEmail = rs.getString("email");
                String fullName = rs.getString("fullName");
                String userName = rs.getString("userName");
                String mobile = rs.getString("mobile");

                this.userPASSWORD_DB_Homepage = rs.getString("password");

                user_email_proPage.setText(userEmail);
                user_fullname_proPage.setText(fullName);
                user_userName_proPage.setText(userName);
                user_mobile_proPage.setText(mobile);

            }

        } catch (Exception e) {
            System.err.println("Got an exception! ");
            System.err.println(e.getMessage());
        }
    }


    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void tabel_booksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_booksMouseClicked
        int i = tabel_books.getSelectedRow();
        TableModel model = tabel_books.getModel();
        //----------------making the panel visiable
        borrowedBooks.setVisible(false);
        ContactPanel.setVisible(false);
        aboutPanel.setVisible(false);
        panelWithTheTable.setVisible(false);
        profilePanel.setVisible(false);
        bookViewPanel.setVisible(true);
        //for borrow book
        this.BookId_HomePage = bookList.get(i).getBookId();

        bookName_Label.setText(bookList.get(i).getBookName());
        authorName_label.setText(bookList.get(i).getAuthorName());
        PublishedDate_label.setText(bookList.get(i).getPublishedDate());
        discriptionTextArea.setText(bookList.get(i).getDiscription());
        //to change buttons
        bookBorrow_button_Change();

    }//GEN-LAST:event_tabel_booksMouseClicked
    private void bookBorrow_button_Change() {
        try {
            // create our mysql database connection
            String myDriver = "com.mysql.cj.jdbc.Driver";
            // change the time zone to UTC
            String myUrl = "jdbc:mysql://localhost/java_login?serverTimezone=UTC";
            Class.forName(myDriver);
            Connection conn = DriverManager.getConnection(myUrl, "root", "");
            pstmt = conn.prepareStatement("select * from bookborrowjava where bookId = ? AND userId= ? AND bookReturned=?");
            pstmt.setInt(1, this.BookId_HomePage);
            pstmt.setInt(2, this.USERID_HomePage);
            pstmt.setInt(3, 0);

            System.out.println("sql query " + pstmt.toString());
            ResultSet rs = pstmt.executeQuery();

            int rowCount_BookBorrow = 0;

            while (rs.next()) {
                rowCount_BookBorrow++;
            }
            if (rowCount_BookBorrow <= 0) {
                this.bookBorrow_Button.setVisible(true);
                this.return_Book_Button.setVisible(false);
            } else if (rowCount_BookBorrow > 0) {
                this.bookBorrow_Button.setVisible(false);
                this.return_Book_Button.setVisible(true);
            }

        } catch (Exception e) {
            System.err.println("Got an exception! ");
            System.err.println(e.getMessage());
        }
    }


    private void borrowed_Books_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrowed_Books_tableMouseClicked
        int i = borrowed_Books_table.getSelectedRow();
        TableModel model = borrowed_Books_table.getModel();
        //----------------making the panel visiable
        borrowedBooks.setVisible(false);
        ContactPanel.setVisible(false);
        aboutPanel.setVisible(false);
        panelWithTheTable.setVisible(false);
        profilePanel.setVisible(false);
        bookViewPanel.setVisible(true);
        //for borrow book
        this.BookId_HomePage = borrowedBookslist.get(i).getBookId();

        bookName_Label.setText(borrowedBookslist.get(i).getBookName());
        authorName_label.setText(borrowedBookslist.get(i).getAuthorName());
        PublishedDate_label.setText(borrowedBookslist.get(i).getPublishedDate());
        discriptionTextArea.setText(borrowedBookslist.get(i).getDiscription());
        //to change buttons
        bookBorrow_button_Change();

    }//GEN-LAST:event_borrowed_Books_tableMouseClicked
    private void changePWfunction() {
        if (this.user_currentPW_proPage.getText().trim().isEmpty() || this.user_newPW_proPage.getText().trim().isEmpty() || this.user_newPWReEnter_proPage.getText().trim().isEmpty()) {
            this.changepw_errorMSG.setForeground(new Color(255, 0, 0));
            changepw_errorMSG.setText("Empty Field");
        } else if (!this.user_currentPW_proPage.getText().equals(this.userPASSWORD_DB_Homepage)) {
            this.changepw_errorMSG.setForeground(new Color(255, 0, 0));
            changepw_errorMSG.setText("Entered Password Is Wrong");
        } else if (!this.user_newPW_proPage.getText().equals(this.user_newPWReEnter_proPage.getText())) {
            this.changepw_errorMSG.setForeground(new Color(255, 0, 0));
            changepw_errorMSG.setText("New Passwords Does Not Match");
        } else {
            String newPassword = this.user_newPW_proPage.getText();
            try {
                // create our mysql database connection
                String myDriver = "com.mysql.cj.jdbc.Driver";
                // change the time zone to UTC
                String myUrl = "jdbc:mysql://localhost/java_login?serverTimezone=UTC";
                Class.forName(myDriver);
                Connection conn = DriverManager.getConnection(myUrl, "root", "");
                pstmt = conn.prepareStatement("UPDATE users SET password = ? WHERE userId = ?;");
                pstmt.setString(1, newPassword);
                pstmt.setInt(2, this.USERID_HomePage);
                System.out.println("sql query " + pstmt.toString());
                pstmt.executeUpdate();
                this.changepw_errorMSG.setForeground(new Color(0, 204, 0));
                this.changepw_errorMSG.setText("...Password Update Successful...");

            } catch (Exception e) {
                System.err.println("Got an exception! ");
                System.err.println(e.getMessage());
            }
        }
    }
    private void bookBorrow_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookBorrow_ButtonMouseClicked
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd");
        LocalDateTime now = LocalDateTime.now();
        LocalDateTime returnDate = LocalDateTime.now().plusDays(7);

        String borrowedDateDB = dtf.format(now);
        String returnDateDB = dtf.format(returnDate);

        System.out.println("UserId = " + this.USERID_HomePage);
        System.out.println("BookId = " + this.BookId_HomePage);
        System.out.println("borrowed Date = " + dtf.format(now));
        System.out.println("return Date = " + dtf.format(returnDate));

        try {
            // create our mysql database connection
            String myDriver = "com.mysql.cj.jdbc.Driver";
            // change the time zone to UTC
            String myUrl = "jdbc:mysql://localhost/java_login?serverTimezone=UTC";
            Class.forName(myDriver);
            Connection conn = DriverManager.getConnection(myUrl, "root", "");
            pstmt = conn.prepareStatement("INSERT INTO bookBorrowjava (userId,bookId,borrowdate,returnDate,bookReturned)  VALUES (?,?,?,?,?)");
            pstmt.setInt(1, this.USERID_HomePage);
            pstmt.setInt(2, this.BookId_HomePage);
            pstmt.setString(3, borrowedDateDB);
            pstmt.setString(4, returnDateDB);
            pstmt.setInt(5, 0);
            System.out.println("sql query " + pstmt.toString());
            pstmt.executeUpdate();

        } catch (Exception e) {
            System.err.println("Got an exception! ");
            System.err.println(e.getMessage());
        }
        //change buttton visibility
        this.bookBorrow_Button.setVisible(false);
        this.return_Book_Button.setVisible(true);
    }//GEN-LAST:event_bookBorrow_ButtonMouseClicked

    private void return_Book_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_return_Book_ButtonMouseClicked
        try {
            // create our mysql database connection
            String myDriver = "com.mysql.cj.jdbc.Driver";
            // change the time zone to UTC
            String myUrl = "jdbc:mysql://localhost/java_login?serverTimezone=UTC";
            Class.forName(myDriver);
            Connection conn = DriverManager.getConnection(myUrl, "root", "");
            pstmt = conn.prepareStatement("UPDATE bookborrowjava SET bookReturned =? WHERE bookId=? AND userId=?");
            pstmt.setInt(1, 1);
            pstmt.setInt(2, this.BookId_HomePage);
            pstmt.setInt(3, this.USERID_HomePage);
            System.out.println("sql query " + pstmt.toString());
            pstmt.executeUpdate();

        } catch (Exception e) {
            System.err.println("Got an exception! ");
            System.err.println(e.getMessage());
        }
        this.bookBorrow_Button.setVisible(true);
        this.return_Book_Button.setVisible(false);
    }//GEN-LAST:event_return_Book_ButtonMouseClicked

    private void save_profile_button_ProfilePageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_save_profile_button_ProfilePageMouseClicked

        String email = this.user_email_proPage.getText();
        String fullName = this.user_fullname_proPage.getText();
        String userName = this.user_userName_proPage.getText();
        String mobile = this.user_mobile_proPage.getText();

        //------------to validate email address
        //----------to validate phone number
        MobileValidator mobileValidator = new MobileValidator();
        boolean mobilevalidation = mobileValidator.setMobile(this.user_mobile_proPage.getText());

        int points = 0;

        if (this.user_email_proPage.getText().trim().isEmpty() || this.user_fullname_proPage.getText().trim().isEmpty() || this.user_userName_proPage.getText().trim().isEmpty() || this.user_mobile_proPage.getText().trim().isEmpty()) {
            this.edit_user_error_msg_proMsg.setForeground(new Color(255, 0, 0));
            this.edit_user_error_msg_proMsg.setText("Empty field");
            points++;
        } //        else if (!emailValidation) {
        //            System.out.println("email is not valid");
        //            this.edit_user_error_msg_proMsg.setText("Email is not valid");
        //            this.edit_user_error_msg_proMsg.setForeground(new Color(255, 0, 0));
        //            points++;
        //        }
        else if (!mobilevalidation) {
            System.out.println("mobile is not valid");
            this.edit_user_error_msg_proMsg.setText("Mobile Number is not valid");
            this.edit_user_error_msg_proMsg.setForeground(new Color(255, 0, 0));
            points++;
        }

        System.out.println("points = " + points);
        //changing pw in database
        if (points == 0) {
            try {
                // create our mysql database connection
                String myDriver = "com.mysql.cj.jdbc.Driver";
                // change the time zone to UTC
                String myUrl = "jdbc:mysql://localhost/java_login?serverTimezone=UTC";
                Class.forName(myDriver);
                Connection conn = DriverManager.getConnection(myUrl, "root", "");
                pstmt = conn.prepareStatement("UPDATE users SET email = ?,fullName=?,userName=?,mobile=? WHERE userId = ?;");
                pstmt.setString(1, email);
                pstmt.setString(2, fullName);
                pstmt.setString(3, userName);
                pstmt.setString(4, mobile);
                pstmt.setInt(5, this.USERID_HomePage);
                System.out.println("sql query " + pstmt.toString());
                pstmt.executeUpdate();

                this.edit_user_error_msg_proMsg.setForeground(new Color(0, 204, 0));
                this.edit_user_error_msg_proMsg.setText("...Profile Update Successful...");

            } catch (Exception e) {
                System.err.println("Got an exception! ");
                System.err.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_save_profile_button_ProfilePageMouseClicked

    private void delete_user_label_profilePageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delete_user_label_profilePageMouseClicked
        int choice = JOptionPane.showConfirmDialog(null, "Are sure you want to delete this account?");
        System.out.println(choice);
        if (choice == JOptionPane.YES_OPTION) {
            System.out.println("Login out");
            Login log = new Login();
            log.setVisible(true);
            setVisible(false);
            System.out.println("Deleting the Account");
            try {
                // create our mysql database connection
                String myDriver = "com.mysql.cj.jdbc.Driver";
                // change the time zone to UTC
                String myUrl = "jdbc:mysql://localhost/java_login?serverTimezone=UTC";
                Class.forName(myDriver);
                Connection conn = DriverManager.getConnection(myUrl, "root", "");
                pstmt = conn.prepareStatement("DELETE FROM users WHERE userId=?;");
                pstmt.setInt(1, this.USERID_HomePage);
                System.out.println("sql query " + pstmt.toString());
                pstmt.executeUpdate();
            } catch (Exception e) {
                System.err.println("Got an exception! ");
                System.err.println(e.getMessage());
            }
        } else {
            System.out.println("NOT deleting");
        }
    }//GEN-LAST:event_delete_user_label_profilePageMouseClicked

    private void edit_profile_Button_profilePageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit_profile_Button_profilePageMouseClicked

        //to change cursor
        Cursor typeCursor = new Cursor(Cursor.TEXT_CURSOR);

        //        user_email_proPage.setFocusable(true);
        user_fullname_proPage.setFocusable(true);
        user_mobile_proPage.setFocusable(true);
        user_userName_proPage.setFocusable(true);

        //        user_email_proPage.setCursor(typeCursor);
        user_fullname_proPage.setCursor(typeCursor);
        user_mobile_proPage.setCursor(typeCursor);
        user_userName_proPage.setCursor(typeCursor);

        edit_profile_Button_profilePage.setVisible(false);
        save_profile_button_ProfilePage.setVisible(true);
    }//GEN-LAST:event_edit_profile_Button_profilePageMouseClicked

    private void changePW_Homepage_ProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changePW_Homepage_ProfileMouseClicked
        profilepage_passwordPanel.setVisible(true);
    }//GEN-LAST:event_changePW_Homepage_ProfileMouseClicked

    private void savePW_In_ProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_savePW_In_ProfileMouseClicked
        changePWfunction();
    }//GEN-LAST:event_savePW_In_ProfileMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BookListLabel;
    private javax.swing.JPanel ContactPanel;
    private javax.swing.JTextField PublishedDate_label;
    private javax.swing.JLabel aboutLabel;
    private javax.swing.JPanel aboutPanel;
    private javax.swing.JScrollPane all_Books_table;
    private javax.swing.JTextField authorName_label;
    private javax.swing.JButton bookBorrow_Button;
    private javax.swing.JTextField bookName_Label;
    private javax.swing.JPanel bookViewPanel;
    private javax.swing.JPanel borrowedBooks;
    private javax.swing.JTable borrowed_Books_table;
    private javax.swing.JLabel borrowedbooksLanel;
    private javax.swing.JLabel changePW_Homepage_Profile;
    private javax.swing.JLabel changepw_errorMSG;
    private javax.swing.JLabel contactLabel;
    private javax.swing.JLabel delete_user_label_profilePage;
    private javax.swing.JTextArea discriptionTextArea;
    private javax.swing.JLabel dragLabel;
    private javax.swing.JButton edit_profile_Button_profilePage;
    private javax.swing.JLabel edit_user_error_msg_proMsg;
    private javax.swing.JPanel imagePanelInBookView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel logoutLabel;
    private javax.swing.JPanel panelWithTheTable;
    private javax.swing.JLabel profileLabel;
    private javax.swing.JPanel profilePanel;
    private javax.swing.JPanel profilepage_passwordPanel;
    private javax.swing.JButton return_Book_Button;
    private javax.swing.JButton savePW_In_Profile;
    private javax.swing.JButton save_profile_button_ProfilePage;
    private javax.swing.JTable tabel_books;
    private javax.swing.JPasswordField user_currentPW_proPage;
    private javax.swing.JTextField user_email_proPage;
    private javax.swing.JTextField user_fullname_proPage;
    private javax.swing.JTextField user_mobile_proPage;
    private javax.swing.JPasswordField user_newPWReEnter_proPage;
    private javax.swing.JPasswordField user_newPW_proPage;
    private javax.swing.JTextField user_userName_proPage;
    // End of variables declaration//GEN-END:variables
}
