/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.PreparedStatement;
import control.EmailValidator;
import control.MobileValidator;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import control.UserSigninCON;

/**
 *
 * @author EACMS
 */
public class SignIn extends javax.swing.JFrame {

    int xMouse;
    int yMouse;
    PreparedStatement pstmt;
    PreparedStatement pstmt11;
    int userId_NewUser;

    /**
     * Creates new form SignIn
     */
    public SignIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dragLabel2 = new javax.swing.JLabel();
        exitLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        name = new javax.swing.JTextField();
        nameTag = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        mobile = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        emailTag = new javax.swing.JLabel();
        mobileTag = new javax.swing.JLabel();
        usernameTag1 = new javax.swing.JLabel();
        signin_label = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        passwordRe = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        signinSubmit = new javax.swing.JButton();
        errorMSG = new javax.swing.JLabel();
        passwordREtag = new javax.swing.JLabel();
        passwordTag = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 34));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 51), 5, true));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Register");

        dragLabel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                dragLabel2MouseDragged(evt);
            }
        });
        dragLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dragLabel2MousePressed(evt);
            }
        });

        exitLabel.setBackground(new java.awt.Color(0, 0, 34));
        exitLabel.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        exitLabel.setForeground(new java.awt.Color(102, 255, 255));
        exitLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitLabel.setText("X");
        exitLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitLabel.setOpaque(true);
        exitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLabelMouseClicked(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Gabriola", 2, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 204));
        jLabel2.setText("Book Browser");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(758, 758, 758)
                .addComponent(exitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(dragLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 913, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 40, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(174, 174, 174)
                    .addComponent(jLabel2)
                    .addContainerGap(722, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exitLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(dragLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 8, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(42, 42, 42)
                    .addComponent(jLabel2)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 34));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 51), 5, true));

        jPanel4.setBackground(new java.awt.Color(0, 0, 34));
        jPanel4.setFocusable(false);

        name.setBackground(new java.awt.Color(0, 0, 34));
        name.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 156, 211)));
        name.setOpaque(false);

        nameTag.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        nameTag.setForeground(new java.awt.Color(255, 255, 255));
        nameTag.setText("Name");

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Email");

        jLabel4.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("User Name");

        jLabel5.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Mobile");

        username.setBackground(new java.awt.Color(0, 0, 34));
        username.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        username.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 156, 211)));

        email.setBackground(new java.awt.Color(0, 0, 34));
        email.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        email.setForeground(new java.awt.Color(255, 255, 255));
        email.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 156, 211)));

        mobile.setBackground(new java.awt.Color(0, 0, 34));
        mobile.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        mobile.setForeground(new java.awt.Color(255, 255, 255));
        mobile.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mobile.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 156, 211)));

        nameLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(255, 0, 0));
        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        emailTag.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        emailTag.setForeground(new java.awt.Color(255, 0, 0));
        emailTag.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        mobileTag.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        mobileTag.setForeground(new java.awt.Color(255, 0, 0));
        mobileTag.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        usernameTag1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        usernameTag1.setForeground(new java.awt.Color(255, 0, 0));
        usernameTag1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        signin_label.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        signin_label.setForeground(new java.awt.Color(30, 126, 255));
        signin_label.setText("Already have an account");
        signin_label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signin_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signin_labelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(name)
                            .addComponent(username)
                            .addComponent(email)
                            .addComponent(mobile, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameTag)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(0, 322, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailTag, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mobileTag, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usernameTag1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(signin_label)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(nameTag)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailTag, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addGap(7, 7, 7)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameTag1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mobile, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(mobileTag, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(signin_label))
        );

        jPanel5.setBackground(new java.awt.Color(0, 0, 34));

        jLabel6.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Password");

        password.setBackground(new java.awt.Color(0, 0, 34));
        password.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        password.setForeground(new java.awt.Color(255, 255, 255));
        password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 156, 211)));
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });

        passwordRe.setBackground(new java.awt.Color(0, 0, 34));
        passwordRe.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        passwordRe.setForeground(new java.awt.Color(255, 255, 255));
        passwordRe.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passwordRe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 156, 211)));

        jLabel7.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Re-Enter Password");

        signinSubmit.setBackground(new java.awt.Color(0, 156, 211));
        signinSubmit.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        signinSubmit.setForeground(new java.awt.Color(0, 0, 34));
        signinSubmit.setText("Sign-In");
        signinSubmit.setBorder(null);
        signinSubmit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signinSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinSubmitActionPerformed(evt);
            }
        });

        errorMSG.setForeground(new java.awt.Color(204, 0, 0));
        errorMSG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        passwordREtag.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        passwordREtag.setForeground(new java.awt.Color(255, 0, 0));
        passwordREtag.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        passwordTag.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        passwordTag.setForeground(new java.awt.Color(255, 0, 0));
        passwordTag.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(errorMSG, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(passwordRe, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(password, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(signinSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordREtag, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordTag, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(8, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordTag, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(passwordREtag, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(passwordRe, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(errorMSG, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(signinSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dragLabel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragLabel2MouseDragged

        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_dragLabel2MouseDragged

    private void dragLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragLabel2MousePressed

        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_dragLabel2MousePressed

    private void exitLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitLabelMouseClicked

    private void signin_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signin_labelMouseClicked

        Login login2 = new Login();
        login2.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_signin_labelMouseClicked

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void signinSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinSubmitActionPerformed
        EmailValidator emailValidator = new EmailValidator();
        boolean emailValidation = emailValidator.setEmail(this.email.getText());
        //----------to validate phone number
        MobileValidator mobileValidator = new MobileValidator();
        boolean mobilevalidation = mobileValidator.setMobile(this.mobile.getText());

        String name = this.name.getText();
        String UserName = this.username.getText();
        String email = this.email.getText();
        String mobile = this.mobile.getText();
        String Password = this.password.getText();
        String passwordRE = this.passwordRe.getText();
        int marks = 0;

        if (this.name.getText().trim().isEmpty()) {
            //            errorMSG.setText("Empty Username !");
            nameLabel.setText("*");
        }
        if (this.email.getText().trim().isEmpty()) {
            emailTag.setText("*");
        }
        if (this.username.getText().trim().isEmpty()) {
            usernameTag1.setText("*");
        }
        if (this.mobile.getText().trim().isEmpty()) {
            mobileTag.setText("*");
        }
        if (this.password.getText().trim().isEmpty()) {
            passwordTag.setText("*");
        }
        if (this.passwordRe.getText().trim().isEmpty()) {
            passwordREtag.setText("*");
        }

        if (!this.name.getText().trim().isEmpty()) {
            nameLabel.setText("");
            marks++;
        }
        if (!this.email.getText().trim().isEmpty()) {
            emailTag.setText("");
            marks++;
        }
        if (!this.username.getText().trim().isEmpty()) {
            usernameTag1.setText("");
            marks++;
        }
        if (!this.mobile.getText().trim().isEmpty()) {
            mobileTag.setText("");
            marks++;
        }
        if (!this.password.getText().trim().isEmpty()) {
            passwordTag.setText("");
            marks++;
        }
        if (!this.passwordRe.getText().trim().isEmpty()) {
            passwordREtag.setText("");
            marks++;
        }
        if (Password.equals(passwordRE)) {
            errorMSG.setText("");
        } else if (!Password.equals(passwordRE)) {
            errorMSG.setText("Passwords does not match !");
            marks--;
        }
        System.out.println("markes = " + marks);

        if (marks == 6) {
            if (!emailValidation) {
                System.out.println("wromg email");
                errorMSG.setText("Email is not valid !");
            } else if (!mobilevalidation) {
                System.out.println("wrong mobile");
                errorMSG.setText("Moble Number is not valid !");
            } else {
                System.out.println(name + UserName + email + mobile + Password + passwordRE);
                canSignIn(name, UserName, email, mobile, Password);
            }
        }

    }//GEN-LAST:event_signinSubmitActionPerformed
    public void canSignIn(String name, String UserName, String email, String mobile, String Password) {
        try {
            int USERID = UserSigninCON.userSignin(name, UserName, email, mobile, Password);
            if (USERID == -3) {
                errorMSG.setText("Email Already taken !");
            } else if (USERID > -1) {
                this.userId_NewUser = USERID;
                JOptionPane.showMessageDialog(null, "Sign-in Successfull !");
//making homepage visiable
                HomePage homePage = new HomePage();
                homePage.setUSERID_HomePage(this.userId_NewUser);
                homePage.setVisible(true);
                setVisible(false);
            }
        } catch (Exception e) {
            System.err.println("Got an exception! ");
            System.err.println(e.getMessage());
            errorMSG.setText(e.getMessage());
        }

        System.out.println("canlogin Loaded");
//        try {
//            // create our mysql database connection
//            String myDriver = "com.mysql.cj.jdbc.Driver";
//            // change the time zone to UTC
//            String myUrl = "jdbc:mysql://localhost/java_login?serverTimezone=UTC";
//            Class.forName(myDriver);
//            Connection conn = DriverManager.getConnection(myUrl, "root", "");
//
//            pstmt11 = conn.prepareStatement("select * from users where email = ? ");
//            pstmt11.setString(1, email);
//            System.out.println("sql query " + pstmt11.toString());
//            ResultSet rs11 = pstmt11.executeQuery();
//
//            int rowCount = 0;
//            while (rs11.next()) {
//                rowCount++;
//            }
//            if (rowCount > 0) {
//                errorMSG.setText("Email Already taken !");
//                System.out.println("row count" + rowCount);
//            }
//            if (rowCount == 0) {
//
//                pstmt = conn.prepareStatement("INSERT INTO users (email,fullName,userName,mobile,password)  VALUES (?,?,?,?,?)");
//                pstmt.setString(1, email);
//                pstmt.setString(2, name);
//                pstmt.setString(3, UserName);
//                pstmt.setString(4, mobile);
//                pstmt.setString(5, Password);
//                System.out.println("sql query " + pstmt.toString());
//                pstmt.executeUpdate();
//
//                gettingUId(email, Password);
//
//                JOptionPane.showMessageDialog(null, "Sign-in Successfull !");
////making homepage visiable
//                HomePage homePage = new HomePage();
//                homePage.setUSERID_HomePage(this.userId_NewUser);
//                homePage.setVisible(true);
//                setVisible(false);
//                pstmt.close();
//            }
//        } catch (Exception e) {
//            System.err.println("Got an exception! ");
//            System.err.println(e.getMessage());
//            errorMSG.setText(e.getMessage());
//        }
    }

//    public void gettingUId(String email, String password) {
//        try {
//            // create our mysql database connection
//            String myDriver = "com.mysql.cj.jdbc.Driver";
//            // change the time zone to UTC
//            String myUrl = "jdbc:mysql://localhost/java_login?serverTimezone=UTC";
//            Class.forName(myDriver);
//            Connection conn = DriverManager.getConnection(myUrl, "root", "");
//            pstmt = conn.prepareStatement("select * from users where email = ? AND password= ?");
//            pstmt.setString(1, email);
//            pstmt.setString(2, password);
//
//            System.out.println("sql query " + pstmt.toString());
//            ResultSet rs = pstmt.executeQuery();
//            int rowCount = 0;
//
//            while (rs.next()) {
//                rowCount++;
//                this.userId_NewUser = rs.getInt("userId");
//                System.out.println(userId_NewUser);
//            }
//        } catch (Exception e) {
//            System.err.println("Got an exception! ");
//            System.err.println(e.getMessage());
//            errorMSG.setText(e.getMessage());
//        }
//    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dragLabel2;
    private javax.swing.JTextField email;
    private javax.swing.JLabel emailTag;
    private javax.swing.JLabel errorMSG;
    private javax.swing.JLabel exitLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField mobile;
    private javax.swing.JLabel mobileTag;
    private javax.swing.JTextField name;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel nameTag;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel passwordREtag;
    private javax.swing.JPasswordField passwordRe;
    private javax.swing.JLabel passwordTag;
    private javax.swing.JButton signinSubmit;
    private javax.swing.JLabel signin_label;
    private javax.swing.JTextField username;
    private javax.swing.JLabel usernameTag1;
    // End of variables declaration//GEN-END:variables
}
